export const FETCH_EVENTS = "FETCH_EVENTS";
export const DELETE_EVENT_BY_EVENT_ID = "DELETE_EVENT_BY_EVENT_ID";
export const CREATE_EVENT = "CREATE_EVENT";
export const GET_EVENT_DETAILS = "GET_EVENT_DETAILS";
